# Generated by Django 3.2.22 on 2024-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaSocial_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_min', models.FloatField()),
                ('rango_max', models.FloatField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
