# Generated by Django 3.2.22 on 2024-05-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_pg_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_cat',
            name='sem12',
        ),
    ]
