# Generated by Django 3.2.22 on 2024-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_pg_cat_sem12'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemMin_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_2021', models.IntegerField()),
                ('y_2022', models.IntegerField()),
                ('y_2023', models.IntegerField()),
                ('y_2024', models.IntegerField()),
                ('y_2025', models.IntegerField()),
                ('y_2026', models.IntegerField()),
                ('y_2027', models.IntegerField()),
                ('y_2028', models.IntegerField()),
                ('y_2029', models.IntegerField()),
                ('y_2030', models.IntegerField()),
                ('y_2031', models.IntegerField()),
            ],
        ),
    ]
