# Generated by Django 3.2.22 on 2024-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_semmin_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisiones_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afore', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
    ]
