# Generated by Django 3.2.22 on 2024-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_comisiones_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentasVitalicias_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('Ax_h', models.FloatField()),
                ('Ax_m', models.FloatField()),
            ],
        ),
    ]
